### ISSUE TITLE
[SUPPORT] ios app can't connect to server

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat.iOS#2418]
@vozerov commented on [Tue Dec 11 2018](https://github.com/RocketChat/Rocket.Chat/issues/12912)

### Description:

ios mobile app can't connect to server. The message is "Oops, can't connect to server"

### Steps to reproduce:

Try to connect to rc.inmyroom.ru

### Server Setup Information:

Rocket chat is deployed using docker.
Server version is 0.72.2
Ubuntu 16.04
Nginx 1.15.7

### Additional context

Nginx is setup as reverse proxy with letsencrypt ssl certificate installed. Nginx config was taken from issues thread at github (also tried config from official docs with no luck).

### Relevant logs:

Websocket works fine as i see:

```

vozerov@mba:~ $ curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: rc.inmyroom.ru" -H "Origin: rc.inmyroom.ru" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://rc.inmyroom.ru/websocket
�{"server_id":"0"}
^C
vozerov@mba:~ $ curl -D - -s https://rc.inmyroom.ru/api/v1/info
HTTP/1.1 200 OK
Server: nginx/1.15.7
Date: Tue, 11 Dec 2018 13:21:37 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
X-Instance-ID: axKHwC6ADyQzG8FH3
Access-Control-Allow-Origin: *
Cache-Control: no-store
Pragma: no-cache
Vary: Accept-Encoding

{"info":{"version":"0.72.2"},"success":true}
vozerov@mba:~ $

```

---

@tassoevan commented on [Tue Dec 11 2018](https://github.com/RocketChat/Rocket.Chat/issues/12912#issuecomment-446212053)

@RocketChat/ios

**Comment by rafaelks** [comment]
@vozerov Problem is that your WebSocket connection upgrade is timing out the request... for me, this request is taking 47 seconds. Do you know what could be happening?

**Comment by vozerov** [comment]
@rafaelks hm.. don't see any errors in neither rocketchat nor mongodb logs. Can you provide the query so i'll try to debug it somehow?

Thanks!

**Comment by rafaelks** [comment]
@vozerov I don't think the problem is related to MongoDB, but actually your server setup. I'll invite our @RocketChat/cloud team here, maybe they can help us.

**Comment by vozerov** [comment]
@rafaelks thanks!

Just to clarify going to post current configs here:

1. docker info: Server Version: 17.12.0-ce
2. ubuntu: DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
3. docker-compose: docker-compose version 1.19.0, build 9e633ef
4. docker-compose.yml:
```

mongo:
  image: mongo
  volumes:
    - /data/mongodb/data:/data/db
    - /data/mongodb/dump:/dump
  command: mongod --smallfiles

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://rc.inmyroom.ru
    - Accounts_UseDNSDomainCheck=True
  links:
    - mongo:db
  ports:
    - 3000:3000

hubot:
  image: rocketchat/hubot-rocketchat:latest
  environment:
    - ROCKETCHAT_URL=136.243.67.215:3000
    - ROCKETCHAT_ROOM=GENERAL
    - ROCKETCHAT_USER=jarvis
    - ROCKETCHAT_PASSWORD=password
    - BOT_NAME=jarvis
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings
  links:
    - rocketchat:rocketchat
  ports:
    - 3001:8080

```
5. nginx config:
```
# Upstreams
upstream backend {
    server 127.0.0.1:3000;
}

server {
	listen 80;
	server_name rc.inmyroom.ru;

        location /.well-known/acme-challenge {
          root /opt/www/acme-root;
          break;
        }

	location / {
		return 301 https://$host$request_uri;
	}
}

# HTTPS Server
server {
    listen 443 ssl;
    server_name rc.inmyroom.ru;

    client_max_body_size 200M;

    error_log /var/log/nginx/rc.inmyroom.ru.access.log;

    ssl_certificate /etc/letsencrypt/live/rc.inmyroom.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rc.inmyroom.ru/privkey.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    location / {
        proxy_pass http://backend/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
    }
}

```

6. Server's load is ok - LA is about 0.5 with 8 cores.

Thanks!
